### ISSUE TITLE
Good Works！

### ISSUE THREAD

**Issue by BlueBlueFF** [claws-lab/projection-in-MLLMs#1]
Any ablation study of with /wo freeze vit encoder? Visual domain-specific info may from vit encoder.

**Comment by gaurav22verma** [comment]
Hi! Thanks for the question. Since the aim is to understand the role of the projection and the LLM parameters, we keep the vision encoder (CLIP) frozen in all the settings. There are results on zero-shot capabiltiies of the vision encoder in Table 1 (CLIP-ZS) and vision-only classification (CLIP embeddings + MLP) in A.3 – they are there to quantify how much domain-specific info is encoded in the vision encoder. Hope this helps!
